#=================================================================================================================================
#Even Fibonacci numbers
#=================================================================================================================================  
#Problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
###################################################################################################################################

#fibonacci(4) vrne 4 element v zaporedju tj. 5
def fibonacci(n): 
    if n <= 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)
    

fib = [] #list vseh sodih fibonaccijevih števil
i = 0 
while fibonacci(i) < 4000000:
    if fibonacci(i) % 2 == 0: #če je sodo št
        fib.append(fibonacci(i))
    i += 1

print(sum(fib)) #4613732
